export enum ApiStatus {
	AVAILABLE = 'AVAILABLE',
	UNAVAILABLE = 'UNAVAILABLE',
	CONNECTING = 'CONNECTING',
	LIMITED = 'LIMITED',
	ERROR = 'ERROR'
}

export enum CallState {
	INITIALIZED = 'INITIALIZED',
	INITIALIZING = 'INITIALIZING',
	DISCONNECTED = 'DISCONNECTED',
	CONNECTED = 'CONNECTED',
	CALLING = 'CALLING',
	CALL_INCOMING = 'CALL_INCOMING',
	CALL_ESTABLISHED = 'CALL_ESTABLISHED',
	CALL_TERMINATING = 'CALL_TERMINATING',
	CALL_TERMINATED = 'CALL_TERMINATED',
	CALL_FAILED = 'CALL_FAILED',
	CALL_REJECTED = 'CALL_REJECTED',
	CALL_REDIRECTED = 'CALL_REDIRECTED'
}

export enum DeviceType {
	DESKTOP = 'DESKTOP',
	IPHONE = 'IPHONE',
	ANDROID = 'ANDROID',
	TABLET = 'TABLET'
}
