import { type CarbonIconProps } from 'carbon-icons-svelte';
import type { Component } from 'svelte';
import type { CallState } from './enums';
import type { RegistererState } from 'sip.js';
import { ApiStatus } from './enums';
import type { LngLatLike } from 'maplibre-gl';

export interface TabItem {
	title: string;
	slug: string;
	icon?: Component<CarbonIconProps>;
	content: InfoBoxItem[];
}

export interface CityConfig {
	slug: string;
	name: string;
	defaultLocale: string;
	bounds: [number, number, number, number];
	center: [number, number];
	minzoom: number;
	maxzoom: number;
	/** Highest zoom the map allows; beyond `maxzoom` the tiles are overzoomed. null = MapLibre default */
	mapMaxZoom: number | null;
	/** Base map style; missing in city.json packaged before it existed */
	mapStyle?: 'positron' | 'terrain';
	fallbackCoordinates: [number, number];
	/** From poi/poi-map.json of the city, {} if it has none */
	poiMap: PoiMap;
}

/** A value in the POI data, compared case-insensitively as text (so 0 also matches "0") */
type PoiMatchValue = string | number;

interface PoiFieldBase {
	/** Translation key below map.popup.labels, or plain text if there is no such key */
	label: string;
	/** Further properties to read, in order, if the property itself is empty */
	alsoTry?: string[];
}

/**
 * How the map popup shows one property of a POI. Rows without a value are left out, unless a
 * `fallback` (translation key below map.popup.values, or plain text) is set.
 */
export type PoiField =
	| (PoiFieldBase & {
			/** ✓ if the value is in `truthy`; ✗ if it is in `falsy`, or for any other value if `falsy` is not set */
			valueToDisplay: 'boolean';
			truthy: PoiMatchValue | PoiMatchValue[];
			falsy?: PoiMatchValue | PoiMatchValue[];
	  })
	| (PoiFieldBase & {
			/** The value as it is in the data */
			valueToDisplay: 'text';
			fallback?: string;
	  })
	| (PoiFieldBase & {
			/** values[value] (translation key below map.popup.values, or plain text); unlisted values as they are */
			valueToDisplay: 'map';
			values: Record<string, string>;
			fallback?: string;
	  });

/** POI file name without .json (e.g. "toilets") → property → how the popup shows it */
export type PoiMap = Record<string, Record<string, PoiField>>;

/** /city/city.json, generated by scripts/package-city.js (or the dev server) */
export interface CityManifest extends CityConfig {
	/** Layout version of the city package, see SCHEMA_VERSION in scripts/lib/city.js */
	schemaVersion: number;
	/** Changes whenever any file of the city data changes */
	dataVersion: string;
	/** All files of the city data, relative to /city/ */
	files: string[];
}

export interface Mode {
	status: number;
	isEmergency: boolean;
	coordinates: LngLatLike;
}

export interface InfoBoxItem {
	title: string;
	textBodyOrList: string | string[];
	links: Link[];
}

export interface Link {
	href?: string;
	target?: string;
	text: string;
}

export interface NetworkServiceState {
	isCaptivePortal: boolean;
	errorMessage: string | null;
	lastPingTime: Date | null;
	apiStatus: ApiStatus;
	mode: Mode | null;
	coordinates: string[];
}

export interface CallServiceState {
	callState: CallState;
	registererState: RegistererState;
	errorMessage: string | null;
	callerId: string | null;
	isMicrophoneMuted: boolean;
	isSpeakerMuted: boolean;
	callDuration: number;
	remoteStream: MediaStream | null;
	localHTMLAudioElement: HTMLAudioElement | null;
}

export type State = 'idle' | 'pending' | 'success' | 'error';

export type SIPUser = {
	username: string;
	password: string;
	timestamp: number;
	displayName?: string;
};

export type SessionResponse = {
	extension: string | number;
	password: string;
	timestamp: number;
};
