// src/lib/config/city.ts
// Generated by scripts/prepare-city.js from cities/<PUBLIC_CITY>/
import cityData from '$lib/generated/city.json';
import type { CityConfig } from '$lib/types';

export const CITY = cityData as CityConfig;
